services:
  synthea:
    build: .
    volumes: 
      - ./synthea:/home/ubuntu/synthea
      - ./output:/home/ubuntu/output/new_path
    command: 'java -jar /home/ubuntu/synthea-with-dependencies.jar -p 10 --exporter.baseDirectory="/home/ubuntu/output/new_path"'