exporter.fhir.export = false
exporter.hospital.fhir.export = false
exporter.csv.export = true
exporter.csv.folder_per_run = true
exporter.years_of_history = 5
exporter.baseDirectory = /home/ubuntu/output