exporter.fhir.export = false
exporter.hospital.fhir.export = false
exporter.csv.export = true
exporter.csv.folder_per_run = false
generate.thread_pool_size = 1
exporter.baseDirectory = /home/ubuntu/output